language: node_js
sudo: required
node_js:
  - "7.4.0"

addons:
    apt:
      update: true
    chrome: stable

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - npm install
    - npm install -g ionic cordova

script:
  - npm run lint
  - npm run build
  - npm run test-ci
  #  - ionic cordova platform add android
  #  - ionic cordova build android
  #  - grep -r -i --include \*.apk .

