language: node_js
sudo: required
node_js:
  - "7.4.0"

addons:
    apt:
      update: true
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
    - npm install
    - npm install -g ionic cordova

script:
  - npm run lint
  - npm run build
  - npm run test-ci
  #  - ionic cordova platform add android
  #  - ionic cordova build android
  #  - grep -r -i --include \*.apk .

