language: android
sudo: required
jdk:
    - oraclejdk8
addons:
    chrome: stable
    apt:
      update: true
env:
    global:
      - ANDROID_TOOLS=${ANDROID_HOME}/tools

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_install:
    - nvm install 6
    # ensure at least gradle 3.3 is in place.
    - node --version
android:
    components:
      - tools

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

install:
    - npm install
    - npm install -g ionic cordova

script:
  - npm run lint
  - npm run build
  - npm run test-ci
  - ionic cordova platform add android
  - ionic cordova build android
  - grep -r -i --include \*.apk .

