sudo: false

language: android
cache:
  directories:
    - node_modules

android:
    components:
        - build-tools-23.0.1
        - android-23

install:
  - npm install -g bower cordova ionic
  - npm install
  - bower update

script:
  - npm run lint
  - npm run build
  - ionic cordova platform add android
  - ionic cordova build android
  - grep -r -i --include \*.apk .

